# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Swerve' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swerve

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'FirebaseUI/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
end
